In [5]:
import tensorflow as tf
import random

In [6]:
def generate_board(n_rows=6, n_cols=7):
    values = (0, 1, 2)
    return [
        [random.choice(values) for _ in range(n_cols)]
        for _ in range(n_rows)
    ]

In [7]:
board = generate_board()
board = tf.convert_to_tensor(board)
board

<tf.Tensor: shape=(6, 7), dtype=int32, numpy=
array([[1, 1, 2, 0, 2, 2, 2],
       [0, 0, 2, 1, 1, 1, 1],
       [0, 0, 2, 0, 2, 0, 1],
       [0, 2, 1, 1, 0, 0, 0],
       [0, 2, 1, 0, 0, 0, 2],
       [0, 0, 0, 2, 2, 2, 0]], dtype=int32)>

In [8]:
flat = tf.reshape(board, shape=(-1))
flat

<tf.Tensor: shape=(42,), dtype=int32, numpy=
array([1, 1, 2, 0, 2, 2, 2, 0, 0, 2, 1, 1, 1, 1, 0, 0, 2, 0, 2, 0, 1, 0,
       2, 1, 1, 0, 0, 0, 0, 2, 1, 0, 0, 0, 2, 0, 0, 0, 2, 2, 2, 0],
      dtype=int32)>

In [9]:
boards = [
    tf.cast(flat == 1, dtype='float16'),
    tf.cast(flat == 2, dtype='float16')
]
boards = tf.convert_to_tensor(boards)
boards

<tf.Tensor: shape=(2, 42), dtype=float16, numpy=
array([[1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 0., 0.,
        0., 0., 0., 0., 1., 0., 0., 1., 1., 0., 0., 0., 0., 0., 1., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 1., 1., 1., 0., 0., 1., 0., 0., 0., 0., 0., 0.,
        1., 0., 1., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0.,
        0., 0., 1., 0., 0., 0., 1., 1., 1., 0.]], dtype=float16)>

In [43]:
tf.stack([
    # player 1's moves
    tf.cast(flat == 1, dtype='float16'),
    # player 2's moves
    tf.cast(flat == 2, dtype='float16')
], axis=-1)

<tf.Tensor: shape=(42, 2), dtype=float16, numpy=
array([[1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 0.],
       [0., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 0.],
       [0., 0.],
       [0., 1.],
       [0., 0.],
       [0., 1.],
       [0., 0.],
       [1., 0.],
       [0., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 1.],
       [1., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 1.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 0.]], dtype=float16)>

In [10]:
tf.reshape(tf.concat(boards, axis=0), shape=(2, 6, 7))

<tf.Tensor: shape=(2, 6, 7), dtype=float16, numpy=
array([[[1., 1., 0., 0., 0., 0., 0.],
        [0., 0., 0., 1., 1., 1., 1.],
        [0., 0., 0., 0., 0., 0., 1.],
        [0., 0., 1., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 1., 0., 1., 1., 1.],
        [0., 0., 1., 0., 0., 0., 0.],
        [0., 0., 1., 0., 1., 0., 0.],
        [0., 1., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0., 1.],
        [0., 0., 0., 1., 1., 1., 0.]]], dtype=float16)>

In [11]:
reshaped_1 = tf.reshape(tf.concat(boards, axis=0), shape=(6, 7, 2))
reshaped_1

<tf.Tensor: shape=(6, 7, 2), dtype=float16, numpy=
array([[[1., 1.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [1., 1.],
        [1., 1.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [1., 0.],
        [0., 1.],
        [1., 0.],
        [0., 0.]],

       [[0., 0.],
        [1., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [1., 0.],
        [1., 1.],
        [1., 0.],
        [0., 1.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [1., 0.],
        [1., 0.],
        [0., 0.],
        [1., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 1.],
        [0., 0.],
        [0., 0.],
        [1., 0.],
        [0., 0.],
        [1., 1.],
        [1., 0.]]], dtype=float16)>

In [12]:
reshaped_2 = tf.reshape(tf.convert_to_tensor(boards), shape=(6, 7, 2))
reshaped_2

<tf.Tensor: shape=(6, 7, 2), dtype=float16, numpy=
array([[[1., 1.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [1., 1.],
        [1., 1.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [1., 0.],
        [0., 1.],
        [1., 0.],
        [0., 0.]],

       [[0., 0.],
        [1., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [1., 0.],
        [1., 1.],
        [1., 0.],
        [0., 1.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [1., 0.],
        [1., 0.],
        [0., 0.],
        [1., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 1.],
        [0., 0.],
        [0., 0.],
        [1., 0.],
        [0., 0.],
        [1., 1.],
        [1., 0.]]], dtype=float16)>

In [38]:
from keras.api.layers import Input, Lambda, Reshape
from keras.api.models import Model

n_rows = 6
n_cols = 7

def split_player_boards(flat_board):
    return tf.stack([
        # player 1's moves
        tf.cast(flat_board == 1, dtype='float16'),
        # player 2's moves
        tf.cast(flat_board == 2, dtype='float16')
    ], axis=-1)

board_input = Input(shape=(n_rows * n_cols,),
                    name='board')
board_layers = Lambda(function=split_player_boards,
                      output_shape=(n_rows * n_cols, 2))(board_input)
board_layers = Reshape(target_shape=(n_rows, n_cols, 2))(board_layers)

model = Model(inputs=[board_input], outputs=[board_layers])

In [39]:
flat_input = tf.expand_dims(flat, axis=0)
model(flat_input)

<tf.Tensor: shape=(1, 6, 7, 2), dtype=float32, numpy=
array([[[[1., 0.],
         [1., 0.],
         [0., 1.],
         [0., 0.],
         [0., 1.],
         [0., 1.],
         [0., 1.]],

        [[0., 0.],
         [0., 0.],
         [0., 1.],
         [1., 0.],
         [1., 0.],
         [1., 0.],
         [1., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 1.],
         [0., 0.],
         [0., 1.],
         [0., 0.],
         [1., 0.]],

        [[0., 0.],
         [0., 1.],
         [1., 0.],
         [1., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 1.],
         [1., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 1.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 1.],
         [0., 1.],
         [0., 1.],
         [0., 0.]]]], dtype=float32)>

In [283]:
turn_marker1 = tf.constant([1])
turn_marker2 = tf.constant([2])
turn_marker1

<tf.Tensor: shape=(1,), dtype=int32, numpy=array([1], dtype=int32)>

In [284]:
from keras.api.layers import CategoryEncoding, Input
from keras.api.models import Model

turn_input = Input(shape=(1,))
cat_enc = CategoryEncoding(num_tokens=2, output_mode="one_hot")(turn_input - 1)
model = Model(inputs=turn_input, outputs=cat_enc)

In [285]:
model(turn_marker1)

<tf.Tensor: shape=(1, 2), dtype=float32, numpy=array([[1., 0.]], dtype=float32)>

In [286]:
model(turn_marker2)

<tf.Tensor: shape=(1, 2), dtype=float32, numpy=array([[0., 1.]], dtype=float32)>